apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  annotations:
    kompose.cmd: kompose convert
        kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec: 
  replicas: 1
  strategy: 
    type: Recreate
  template: 
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec: 
      containers:
      - image: carpio701021/magento2.3-nginx
        name: nginx
        ports: 
        - containerPort: 8000
        - containerPort: 8443
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: appdata
        securityContext:
          allowPrivilegeEscalation: true
        restartPolicy: Always
        volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: appdata
          securityContext:
            runasuser: 1000
            fsGroup: 1000
status: {}